<?php /*<?php $update_icon = ($this -> has_update()) ? ' <span class="update-plugins count-1"><span class="update-count">1</span></span>' : ''; ?>
<div class="tribulant_plugin_tabs">
	<ul>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings); ?>"><?php esc_html_e('General', 'wp-mailinglist'); ?></a><span class="border-right"></span></li>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings_subscribers) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings_subscribers); ?>"><?php esc_html_e('Subscribers', 'wp-mailinglist'); ?></a><span class="border-right"></span></li>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings_templates) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings_templates); ?>"><?php esc_html_e('System Emails', 'wp-mailinglist'); ?></a><span class="border-right"></span></li>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings_system) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings_system); ?>"><?php esc_html_e('System', 'wp-mailinglist'); ?></a><span class="border-right"></span></li>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings_tasks) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings_tasks); ?>"><?php esc_html_e('Scheduled Tasks', 'wp-mailinglist'); ?></a><span class="border-right"></span></li>
        <li <?php echo (!empty($_GET['page']) && $_GET['page'] == $this -> sections -> settings_updates) ? 'class="active"' : ''; ?>><span class="border-left"></span><a href="?page=<?php echo esc_html( $this -> sections -> settings_updates); ?>"><?php esc_html_e('Updates', 'wp-mailinglist'); ?><?php echo esc_html( $update_icon); ?></a><span class="border-right"></span></li>
    </ul>
</div>*/ ?>