<?php

global $wpdb;

$countriesquery = "INSERT INTO `" . $wpdb -> prefix . "wpmlcountries` (`id`, `value`, `code`, `isocode`) VALUES 
(1, 'Afghanistan', 'AF', 'AFG'),
(2, '&Aring;land Islands', 'AX', 'ALA'),
(3, 'Albania', 'AL', 'ALB'),
(4, 'Algeria', 'DZ', 'DZA'),
(5, 'American Samoa', 'AS', 'ASM'),
(6, 'Andorra', 'AD', 'AND'),
(7, 'Angola', 'AO', 'AGO'),
(8, 'Anguilla', 'AI', 'AIA'),
(9, 'Antarctica', 'AQ', 'ATA'),
(10, 'Antigua and Barbuda', 'AG', 'ATG'),
(11, 'Argentina', 'AR', 'ARG'),
(12, 'Armenia', 'AM', 'ARM'),
(13, 'Aruba', 'AW', 'ABW'),
(14, 'Australia', 'AU', 'AUS'),
(15, 'Austria', 'AT', 'AUT'),
(16, 'Azerbaijan', 'AZ', 'AZE'),
(17, 'Bahamas', 'BS', 'BHS'),
(18, 'Bahrain', 'BH', 'BHR'),
(19, 'Bangladesh', 'BD', 'BGD'),
(20, 'Barbados', 'BB', 'BRB'),
(21, 'Belarus', 'BY', 'BLR'),
(22, 'Belgium', 'BE', 'BEL'),
(23, 'Belize', 'BZ', 'BLZ'),
(24, 'Benin', 'BJ', 'BEN'),
(25, 'Bermuda', 'BM', 'BMU'),
(26, 'Bhutan', 'BT', 'BTN'),
(27, 'Bolivia', 'BO', 'BOL'),
(28, 'Bosnia and Herzegovina', 'BA', 'BIH'),
(29, 'Botswana', 'BW', 'BWA'),
(30, 'Bouvet Island', 'BV', 'BVT'),
(31, 'Brazil', 'BR', 'BRA'),
(32, 'British Indian Ocean territory', 'IO', 'IOT'),
(33, 'Brunei Darussalam', 'BN', 'BRN'),
(34, 'Bulgaria', 'BG', 'BGR'),
(35, 'Burkina Faso', 'BF', 'BFA'),
(36, 'Burundi', 'BI', 'BDI'),
(37, 'Cambodia', 'KH', 'KHM'),
(38, 'Cameroon', 'CM', 'CMR'),
(39, 'Canada', 'CA', 'CAN'),
(40, 'Cape Verde', 'CV', 'CPV'),
(41, 'Cayman Islands', 'KY', 'CYM'),
(42, 'Central African Republic', 'CF', 'CAF'),
(43, 'Chad', 'TD', 'TCD'),
(44, 'Chile', 'CL', 'CHL'),
(45, 'China', 'CN', 'CHN'),
(46, 'Christmas Island', 'CX', 'CXR'),
(47, 'Cocos (Keeling) Islands', 'CC', 'CCK'),
(48, 'Colombia', 'CO', 'COL'),
(49, 'Comoros', 'KM', 'COM'),
(50, 'Congo', 'CG', 'COG'),
(51, 'Congo The Democratic Republic', 'CD', 'COD'),
(53, 'Cook Islands', 'CK', 'COK'),
(54, 'Costa Rica', 'CR', 'CRI'),
(55, 'C&ocirc;te d\'Ivoire (Ivory Coast)', 'CI', 'CIV'),
(56, 'Croatia (Hrvatska)', 'HR', 'HRV'),
(57, 'Cuba', 'CU', 'CUB'),
(58, 'Cyprus', 'CY', 'CYP'),
(59, 'Czech Republic', 'CZ', 'CZE'),
(60, 'Denmark', 'DK', 'DNK'),
(61, 'Djibouti', 'DJ', 'DJI'),
(62, 'Dominica', 'DM', 'DMA'),
(63, 'Dominican Republic', 'DO', 'DOM'),
(64, 'East Timor', 'TL', 'ETL'),
(65, 'Ecuador', 'EC', 'ECU'),
(66, 'Egypt', 'EG', 'EGY'),
(67, 'El Salvador', 'SV', 'SLV'),
(68, 'Equatorial Guinea', 'GQ', 'GNQ'),
(69, 'Eritrea', 'ER', 'ERI'),
(70, 'Estonia', 'EE', 'EST'),
(71, 'Ethiopia', 'ET', 'ETH'),
(72, 'Falkland Islands', 'FK', 'FLK'),
(73, 'Faroe Islands', 'FO', 'FRO'),
(74, 'Fiji', 'FJ', 'FJI'),
(75, 'Finland', 'FI', 'FIN'),
(76, 'France', 'FR', 'FRA'),
(77, 'French Guiana', 'GF', 'GUF'),
(78, 'French Polynesia', 'PF', 'PYF'),
(79, 'French Southern Territories', 'TF', 'ATF'),
(80, 'Gabon', 'GA', 'GAB'),
(81, 'Gambia', 'GM', 'GMB'),
(82, 'Georgia', 'GE', 'GEO'),
(83, 'Germany', 'DE', 'DEU'),
(84, 'Ghana', 'GH', 'GHA'),
(85, 'Gibraltar', 'GI', 'GIB'),
(86, 'Greece', 'GR', 'GRC'),
(87, 'Greenland', 'GL', 'GRL'),
(88, 'Grenada', 'GD', 'GRD'),
(89, 'Guadeloupe', 'GP', 'GLP'),
(90, 'Guam', 'GU', 'GUA'),
(91, 'Guatemala', 'GT', 'GTM'),
(92, 'Guinea', 'GN', 'GIN'),
(93, 'Guinea-Bissau', 'GW', 'GNB'),
(94, 'Guyana', 'GY', 'GUY'),
(95, 'Haiti', 'HY', 'HTI'),
(96, 'Heard and McDonald Islands', 'HM', 'HMD'),
(97, 'Honduras', 'HN', 'HND'),
(98, 'Hong Kong', 'HK', 'HKG'),
(99, 'Hungary', 'HU', 'HUN'),
(100, 'Iceland', 'IS', 'ISL'),
(101, 'India', 'IN', 'IND'),
(102, 'Indonesia', 'ID', 'IDN'),
(103, 'Iran', 'IR', 'IRN'),
(104, 'Iraq', 'IQ', 'IRQ'),
(105, 'Ireland', 'IE', 'IRL'),
(106, 'Israel', 'IL', 'ISR'),
(107, 'Italy', 'IT', 'ITA'),
(108, 'Jamaica', 'JM', 'JAM'),
(109, 'Japan', 'JP', 'JAP'),
(110, 'Jordan', 'JO', 'JOR'),
(111, 'Kazakhstan', 'KZ', 'KAZ'),
(112, 'Kenya', 'KE', 'KEN'),
(113, 'Kiribati', 'KI', 'KIR'),
(114, 'Korea (north)', 'KP', 'PRK'),
(115, 'Korea (south)', 'KR', 'KOR'),
(116, 'Kuwait', 'KW', 'KWT'),
(117, 'Kyrgyzstan', 'KG', 'KGZ'),
(118, 'Lao People\'s Democratic Republic', 'LA', 'LAO'),
(119, 'Latvia', 'LV', 'LVA'),
(120, 'Lebanon', 'LB', 'LBN'),
(121, 'Lesotho', 'LS', 'LSO'),
(122, 'Liberia', 'LR', 'LBR'),
(123, 'Libyan Arab Jamahiriya', 'LY', 'LBY'),
(124, 'Liechtenstein', 'LI', 'LIE'),
(125, 'Lithuania', 'LT', 'LTU'),
(126, 'Luxembourg', 'LU', 'LUX'),
(127, 'Macao', 'MO', 'MAC'),
(128, 'Macedonia', 'MK', 'MKD'),
(129, 'Madagascar', 'MG', 'MDG'),
(130, 'Malawi', 'MW', 'MWI'),
(131, 'Malaysia', 'MY', 'MYS'),
(132, 'Maldives', 'MV', 'MDV'),
(133, 'Mali', 'ML', 'MLI'),
(134, 'Malta', 'MT', 'MLT'),
(135, 'Marshall Islands', 'MH', 'MHL'),
(136, 'Martinique', 'MQ', 'MTQ'),
(137, 'Mauritania', 'MR', 'MRT'),
(138, 'Mauritius', 'MU', 'MUS'),
(139, 'Mayotte', 'YT', 'MYT'),
(140, 'Mexico', 'MX', 'MEX'),
(141, 'Micronesia', 'FM', 'FSM'),
(142, 'Moldova', 'MD', 'MDA'),
(143, 'Monaco', 'MC', 'MCO'),
(144, 'Mongolia', 'MN', 'MNG'),
(145, 'Montserrat', 'MS', 'MSR'),
(146, 'Morocco', 'MA', 'MAR'),
(147, 'Mozambique', 'MZ', 'MOZ'),
(148, 'Myanmar', 'MM', 'MMR'),
(149, 'Namibia', 'NA', 'NAM'),
(150, 'Nauru', 'NR', 'NAU'),
(151, 'Nepal', 'NP', 'NPL'),
(152, 'Netherlands', 'NL', 'NLD'),
(153, 'Netherlands Antilles', 'AN', 'ANT'),
(154, 'New Caledonia', 'NC', 'NCL'),
(155, 'New Zealand', 'NZ', 'NZL'),
(156, 'Nicaragua', 'NI', 'NIC'),
(157, 'Niger', 'NE', 'NER'),
(158, 'Nigeria', 'NG', 'NGA'),
(159, 'Niue', 'NU', 'NIU'),
(160, 'Norfolk Island', 'NF', 'NFK'),
(161, 'Northern Mariana Islands', 'MP', 'MNP'),
(162, 'Norway', 'NO', 'NOR'),
(163, 'Oman', 'OM', 'OMN'),
(164, 'Pakistan', 'PK', 'PAK'),
(165, 'Palau', 'PW', 'PLW'),
(166, 'Palestinian Territories', 'PS', 'PSE'),
(167, 'Panama', 'PA', 'PAN'),
(168, 'Papua New Guinea', 'PG', 'PNG'),
(169, 'Paraguay', 'PY', 'PRY'),
(170, 'Peru', 'PE', 'PER'),
(171, 'Philippines', 'PH', 'PHL'),
(172, 'Pitcairn', 'PN', 'PCN'),
(173, 'Poland', 'PL', 'POL'),
(174, 'Portugal', 'PT', 'PRT'),
(175, 'Puerto Rico', 'PR', 'PRI'),
(176, 'Qatar', 'QA', 'QAT'),
(177, 'R&eacute;union', 'RE', 'REU'),
(178, 'Romania', 'RO', 'ROU'),
(179, 'Russia', 'RU', 'RUS'),
(180, 'Rwanda', 'RW', 'RWA'),
(181, 'Saint Helena', 'SH', 'SHN'),
(182, 'Saint Kitts and Nevis', 'KN', 'KNA'),
(183, 'Saint Lucia', 'LC', 'LCA'),
(184, 'Saint Pierre and Miquelon', 'PM', 'SPM'),
(185, 'Saint Vincent and the Grenadines', 'VC', 'VCT'),
(186, 'Samoa', 'WS', 'WSM'),
(187, 'San Marino', 'SM', 'SMR'),
(188, 'Sao Tome and Principe', 'ST', 'STP'),
(189, 'Saudi Arabia', 'SA', 'SAU'),
(190, 'Senegal', 'SN', 'SEN'),
(191, 'Serbia and Montenegro', 'RS', 'SRB'),
(192, 'Seychelles', 'SC', 'SYC'),
(193, 'Sierra Leone', 'SL', 'SLE'),
(194, 'Singapore', 'SG', 'SGP'),
(195, 'Slovakia', 'SK', 'SVK'),
(196, 'Slovenia', 'SI', 'SVN'),
(197, 'Solomon Islands', 'SB', 'SLB'),
(198, 'Somalia', 'SO', 'SOM'),
(199, 'South Africa', 'ZA', 'ZAF'),
(200, 'South Georgia and the South Sandwich Islands', 'GS', 'SGS'),
(201, 'Spain', 'ES', 'ESP'),
(202, 'Sri Lanka', 'LK', 'LKA'),
(203, 'Sudan', 'SD', 'SDN'),
(204, 'Suriname', 'SR', 'SUR'),
(205, 'Svalbard and Jan Mayen Islands', 'SJ', 'SJM'),
(206, 'Swaziland', 'SZ', 'SWZ'),
(207, 'Sweden', 'SE', 'SWE'),
(208, 'Switzerland', 'CH', 'CHE'),
(209, 'Syrian Arab Republic', 'SY', 'SYR'),
(210, 'Taiwan', 'TW', 'TWN'),
(211, 'Tajikistan', 'TJ', 'TJK'),
(212, 'Tanzania', 'TZ', 'TZA'),
(213, 'Thailand', 'TH', 'THA'),
(214, 'Togo', 'TG', 'TGO'),
(215, 'Tokelau', 'TK', 'TKL'),
(216, 'Tonga', 'TO', 'TON'),
(217, 'Trinidad and Tobago', 'TT', 'TTO'),
(218, 'Tunisia', 'TN', 'TUN'),
(219, 'Turkey', 'TR', 'TUR'),
(220, 'Turkmenistan', 'TM', 'TKM'),
(221, 'Turks and Caicos Islands', 'TC', 'TCA'),
(222, 'Tuvalu', 'TV', 'TUV'),
(223, 'Uganda', 'UG', 'UGA'),
(224, 'Ukraine', 'UA', 'UKR'),
(225, 'United Arab Emirates', 'AE', 'ARE'),
(226, 'United Kingdom', 'GB', 'GBR'),
(227, 'United States', 'US', 'USA'),
(228, 'Uruguay', 'UY', 'URY'),
(229, 'Uzbekistan', 'UZ', 'UZB'),
(230, 'Vanuatu', 'VU', 'VUT'),
(231, 'Vatican City', 'VA', 'VAT'),
(232, 'Venezuela', 'VE', 'VEN'),
(233, 'Vietnam', 'VN', 'VNM'),
(234, 'Virgin Islands (British)', 'VG', 'VGB'),
(235, 'Virgin Islands (US)', 'VI', 'VIR'),
(236, 'Wallis and Futuna Islands', 'WF', 'WLF'),
(237, 'Western Sahara', 'EH', 'ESH'),
(238, 'Yemen', 'YE', 'YEM'),
(240, 'Zambia', 'ZM', 'ZMB'),
(241, 'Zimbabwe', 'ZW', 'ZWE'), 
(242, 'Jersey', 'JE', 'JEY'), 
(243, 'Guernsey', 'GG', 'GGY');";

?>